### ISSUE TITLE
Network output initialization

### ISSUE THREAD

**Issue by dogyoonlee** [facebookresearch/hyperreel#14]
Hello, I appreciate to your awesome work!!

I have a question.

As mentioned in your paper, scalar value **delta** and per-sample point offset **e** are also output of the MLP, which are shared with primitives.

However, how to initialize the above **delta** value as negative value in start of the training?
Should I have to initialize the weight of the MLP network for **delta** value?

![image](https://user-images.githubusercontent.com/62277785/219844720-0633d521-81df-412f-ab6f-f0158d6da349.png)

Thank you for your attention!

**Comment by breuckelen** [comment]
Hi! Thanks for the question -- you can just add a negative shift to the network outputs corresponding to $\delta_1, \dots, \delta_n$. In our work, we use $-4$, which corresponds to an sigmoid-activated value of approximately 0.02.

**Comment by dogyoonlee** [comment]
@breuckelen 
Thank you for your reply!!

However, I have few more question to reimplement your sampling strategy for my revised code!

As I understand, primitive and offset values are predicted by the MLP network.
Then, predicted primitive(scalar z-values for forward-facing scene) is not sorted since it is just predicted by the network.
DId you sort the predicted primitive values along the z-axis? 

In addition, predicted offset and offset window values paired to predicted primitives are also sorted using the sorted index of the primitives?
I think the order of predicted values are important to generate the pixel color based on volume rendering values.

Further more, I implemented final activation function for primitive values using Tanh function since primitive should be {-1~1} on NDC coordinate.

Am I correctly implemented??

Again, I really appreciate to your awesome work and quick reply!!

**Comment by breuckelen** [comment]
Hi! The distances that the primitive intersections produce are in fact sorted. See https://github.com/facebookresearch/hyperreel/blob/main/nlf/intersect/base.py#L205

The other outputs (e.g. point offsets, and window values are _not_ sorted). Our codebase *supports* sorting the other outputs (by adding to the "sort_outputs" list in the intersect config), but in our experiments sorting these outputs didn't improve quality. 

Note, also, that the primitives are initialized in a stratified manner (described in section C of the supplement). In the case of z planes and NDC, they step between [-1, 1]. The outputs of the MLP therefore represent ray-dependent perturbations from these initial primitive parameters, and we use an identity activation for the perturbations, rather than Tanh.
