### ISSUE TITLE
Global color cast of rendered images

### ISSUE THREAD

**Issue by ghy0324** [facebookresearch/hyperreel#17]
Hi! Thanks a lot for sharing your excellent project!
When I run your code on `cook spinach` scene of Neural 3D Video dataset, I found that there exists a global color cast. Namely, the rendered images of all frames are showing a little pinkish, which is distinct when switching between predicted images and ground truth ones. Here is an example.
Is this normal? And what's the possible reason? Looking forward to your reply!

![ground truth](https://user-images.githubusercontent.com/36201670/221860250-68074ab2-e03c-4ce8-ae3e-1c883f7019a8.png)
![prediction](https://user-images.githubusercontent.com/36201670/221860384-8e3f3b06-99f4-4341-a31a-4254ea8cada0.png)

**Comment by breuckelen** [comment]
Hi! This may be due to the imperfect color calibration of the neural 3D video dataset -- there is a noticeable color shift between individual video streams (for example cam20.mp4 and  cam00.mp4 in the cook spinach sequence). Our model will likely absorb these color changes into view dependent color from the dynamic volume (represented as spherical harmonic coefficients), or in the ray-dependent color scale and color shift terms described in section C.4. in the appendix of our work. Unfortunately, because the heldout view is not observed during training, there is no guarantee that this view-dependent color will accurately capture it's color shift of the heldout view (hence the difference that you're observing)
