### ISSUE TITLE
An issues of the choice of tform and bias activation in the paper "Learning Neural Light Fields With Ray Space Embedding"

### ISSUE THREAD

**Issue by dzls952402394** [facebookresearch/hyperreel#30]
Hello, Neural Light Fields is a great job. But I have some questions that I am confused about.
I have seen you have been archived this repository. So I can only come here to ask you.

In your code, you choose row_l2_norm activation which actually used L2 norm to normalize each line of tform matrix, and tanh to normalize bias vector.

Why do you choose these two normalized methods? Is there any other good normalized methods to choose? especially for tform matrix?

**Comment by benattal** [comment]
Sorry for the (very) late response. The row_l2_norm activation is supposed to prevent the transform from shrinking/expanding ray space too much, potentially causing positional encoding on the embedded space to behave strangely. We use tanh in order to bound/reduce the affect of the bias -- the bias has more flexibility to map arbitrary rays to the same point in embedded space, whereas we mostly want to use a (locally constant) linear transform to put intersecting rays in correspondence with one another.
