### ISSUE TITLE
Command and checkpoints for reproducing results in the paper

### ISSUE THREAD

**Issue by hangg7** [facebookresearch/hyperreel#5]
Hi Ben,

Thanks for releasing your code!

I am wondering if you are going to release the pretrained models? It will make it much easier to play with the repo!

On the other hand, what is the command that I should use to, say, reproduce your numbers and results in the neural-3d-video dataset? You mentioned [here]( https://github.com/facebookresearch/hyperreel#neural-3d) that we should specify the "start frame", but to what value? I would assume 0, but it will be nice for the author to specify it. 

Finally, I noticed that for the neural-3d-video dataset, you seem to use a subset of frames instead of the full video. In that case, is the comparison study you showed in the paper still valid? It seems to me that the original neural-3d-video paper use the full res + full video for training and evaluation.

Thanks!

**Comment by hangg7** [comment]
Thanks for your prompt clarification! It makes a lot of sense (sorry that I didn't receive any notifcation that you have replied). My questions are all answered and I am closing the issue here. Thanks for your great work!

**Comment by hangg7** [comment]
A quick follow-up question: You mentioned to split the training video into chunks, is there any particular result for that? Also, since it is chunked, does that mean the training time scales up linearly w.r.t. to the frames? I remember you said the training time is about 1.5h, does that include the training times of all chunks?

**Comment by breuckelen** [comment]
I'm not sure if this is exactly what you're asking but: we don't have an ablation for chunk size, and use 50 frame chunks for all dynamic datasets. Or was there something else you were getting at with your first question?

And yes, that's correct --- we train *every model* for 1.5 hours, which for a dynamic sequence means training the model for each 50 frame subset for 1.5 hours (e.g. 9 hours total for a 10 second video). Since it's not immediately obvious from the text I'll make a note in the README, and be sure to clarify this point in any future revisions of the paper (as it pertains to both the Neural 3D and Google Immersive datasets).

**Comment by hangg7** [comment]
That makes sense. About the first question, I meant "reason" instead pf "result" (oops it's a typo). I would assume it has something to do with the model size?
