### ISSUE TITLE
Two question about this work

### ISSUE THREAD

**Issue by thuanz123** [facebookresearch/hyperreel#8]
Hi, this is a great work and the results are impressive; however, there are two questions that I'm quite stuck in your paper:

1. In section 3.1 page 4, how are the geometry primitives constructed? And why this is more constrained than AdaNeRF? As I don't see anything backing up your claim "if two distinct rays observe the same point in the scene, then the sample network needs only predict one primitive for both rays."
2. In figure 2, it is seem that the TensorRF is not used for rendering so why you introduce it in section 3.2?

**Comment by breuckelen** [comment]
Hi!

Question 1
========
* Consider a point on some surface in the scene and all rays ${r^p_j}$ that observe this point without occlusion. Now consider a primitive $G_p$ (plane, sphere, etc.) that passes through this point. If we calculate the intersection between all of these rays ${r^p_j}$, and the primitive $G_p$ *at least one* of the intersections *will be this point* (since, again, the rays pass through the point). In the case of z planes, *the only* intersection will be this point $p$ (except for a vanishingly small set of rays). In the case of spheres and cameras that lie within some small viewbox, we also have that *the only* intersection will be this point $p$. Therefore, in the cases that we consider, if $G_p$ passes through the point, then $inter(G_p; r^p_j) = p$ for all $j$. 
* As such, the sample network only needs to predict $G_p$ for all of these rays. In AdaNeRF, the distance from the ray origin of each ${r^p_j}$ to the point $p$ is *may be different for every ray* (even if the ray origins are unified, as described in DoNeRF) --- especially for rays that are far apart from one another. Therefore, their sample network needs to activate *different ray segments* for every ray (non constant sample signal for all rays that observe a point) --- whereas the sample signal that we predict can be constant.


Question 2
========
This figure focuses on the sample network scheme and omits the "sample lookup" component of our pipeline described in section 3.2. In particular, we omit how $L_e(x_k, \omega)$ is derived -- and in principle any volume representation can be used in place of a TensoRF. Note that we explain what representation we use for static scenes (TensoRF) in section 3.2.1.

**Comment by thuanz123** [comment]
Hi, thanks for your answer. I have understood the question 2 but question 1 is still unclear to me. From my understanding, you pre-define a set of geometry primitives first then train the sampler to predict the closest primitives that the ray passes through? It would be a great help if you point to the codes where the primitives is involved in the training process.

**Comment by breuckelen** [comment]
Not quite — the primitives are not predefined. The sample network predicts the primitives directly, so that they can vary depending on the input ray (hence, they are ray-conditioned). In the case of forward facing scenes, it predicts the parameters of planes orthogonal to the z-axis. In the case of outward facing scenes, it predicts the radii of spheres centered at the origin.

The code that predicts the parameters of each primitive is located in nlf/embedding/ray.py, the code that makes use of the parameters is defined in nlf/intersect — nlf/intersect/z.py, for example, defines the code for axis-aligned plane intersection.

**Comment by thuanz123** [comment]
Thanks for your fast and helpful response, I'm all clear now
